-- 01. USER 생성 및 권한 부여

CREATE USER adminuser
  PASSWORD = 'Ekdhavy!2345'
  DEFAULT_ROLE = SYSADMIN
  DEFAULT_WAREHOUSE = PO3_WH
  DEFAULT_NAMESPACE = PO3.PUBLIC
  MUST_CHANGE_PASSWORD = TRUE;


-- 02. SYSADMIN 역할을 adminuser에게 부여  
GRANT ROLE SYSADMIN TO USER adminuser;
GRANT USAGE ON DATABASE PO3 TO ROLE SYSADMIN;
GRANT USAGE, MONITOR ON SCHEMA PO3.POPULATION TO ROLE SYSADMIN;

-- 03. 이전 생성되어있던 모든 테이블 및 앞으로 생성될 테이블에 대한 모든 권한 부여
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA PO3.POPULATION TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PO3.POPULATION TO ROLE SYSADMIN;

-- 04. 해당 스키마에 부여된 모든 권한 확인
SHOW GRANTS ON SCHEMA PO3.POPULATION;



-- created_on	privilege	granted_on	name	granted_to	grantee_name	grant_option	granted_by	granted_by_role_type
-- 2025-07-27 22:38:41.856 -0700	OWNERSHIP	SCHEMA	PO3.POPULATION	ROLE	ACCOUNTADMIN	true	ACCOUNTADMIN	ROLE
-- 2025-08-03 16:27:26.497 -0700	CREATE WORKSPACE	SCHEMA	PO3.POPULATION	ROLE	SYSADMIN	false	ACCOUNTADMIN	ROLE
-- 2025-08-03 16:36:44.695 -0700	MONITOR	SCHEMA	PO3.POPULATION	ROLE	SYSADMIN	false	ACCOUNTADMIN	ROLE
-- 2025-08-03 16:36:44.705 -0700	USAGE	SCHEMA	PO3.POPULATION	ROLE	SYSADMIN	false	ACCOUNTADMIN	ROLE