-- 01. MULTI-PULPOSE WAREHOUSE 생성

CREATE OR REPLACE WAREHOUSE PO3_WH
WAREHOUSE_SIZE = 'small'
AUTO_SUSPEND=60
AUTO_RESUME =TRUE;



-- SNOWPARK OPTIMIZATION WAREHOUSE 생성 (모델 학습 시 사용)
CREATE OR REPLACE WAREHOUSE SNOWPARK_OPT_WH WITH
  WAREHOUSE_SIZE = 'MEDIUM'
  WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED';



-- 02. DATABASE & SCHEMA 생성

CREATE OR REPLACE DATABASE PO3;
CREATE OR REPLACE SCHEMA POPULATION;    
USE SCHEMA POPULATION;  


-- 03. NETWORK 정책 적용 (필요시)
-- ALTER ACCOUNT SET NETWORK_POLICY = TEST;

