-- 01. FILE FORMAT 생성 (파일 및 압축 형식 지정)
CREATE OR REPLACE FILE FORMAT file_format
  TYPE = 'PARQUET'
  COMPRESSION = 'AUTO';



-- 02. STAGE 생성 및 확인
CREATE OR REPLACE STAGE TEST_MG_STAGE 
  URL = 's3://nuke-snowflake/test-export/rdsdb/rdsdb.price_table/1'
  STORAGE_INTEGRATION = to_s3_v4
  FILE_FORMAT = file_format;
  
LIST @TEST_MG_STAGE ;


-- 03. AWS RDS SNAPSHOT 데이터를 EXTERNAL TABLE로 변환
CREATE OR REPLACE EXTERNAL TABLE EXT_RDS_SNAPSHOT (
  REGION_LEVEL STRING AS (VALUE:"REGION_LEVEL"::STRING),
  BJD_CODE STRING AS (VALUE:"BJD_CODE"::STRING),
  SD STRING AS (VALUE:"SD"::STRING),
  SGG STRING AS (VALUE:"SGG"::STRING),
  EMD STRING AS (VALUE:"EMD"::STRING),
  TOTAL_HOUSEHOLDS BIGINT AS (VALUE:"TOTAL_HOUSEHOLDS"::BIGINT),
  YYYYMMDD DATE AS (to_date(VALUE:"YYYYMMDD"::STRING, 'YYYY-MM-DD')),
  MEME_PRICE_PER_SUPPLY_PYEONG DOUBLE AS (VALUE:"MEME_PRICE_PER_SUPPLY_PYEONG"::DOUBLE),
  JEONSE_PRICE_PER_SUPPLY_PYEONG DOUBLE AS (VALUE:"JEONSE_PRICE_PER_SUPPLY_PYEONG"::DOUBLE)
)
WITH LOCATION = @TEST_MG_STAGE
FILE_FORMAT = file_format
REFRESH_ON_CREATE = FALSE
AUTO_REFRESH = FALSE;


ALTER EXTERNAL TABLE EXT_RDS_SNAPSHOT REFRESH;



-- 04. EXTERNAL TABLE을 SNOWFLAKE 테이블로 변환하여 사용
CREATE OR REPLACE TABLE  DAILY_REAL_ESTATE_TRADES AS
SELECT
  VALUE:"REGION_LEVEL"::STRING AS REGION_LEVEL,
  VALUE:"BJD_CODE"::STRING AS BJD_CODE,
  VALUE:"SD"::STRING AS SD,
  VALUE:"SGG"::STRING AS SGG,
  VALUE:"EMD"::STRING AS EMD,
  VALUE:"TOTAL_HOUSEHOLDS"::BIGINT AS TOTAL_HOUSEHOLDS,
  TO_DATE(VALUE:"YYYYMMDD"::STRING, 'YYYY-MM-DD') AS YYYYMMDD,
  VALUE:"MEME_PRICE_PER_SUPPLY_PYEONG"::DOUBLE AS MEME_PRICE_PER_SUPPLY_PYEONG,
  VALUE:"JEONSE_PRICE_PER_SUPPLY_PYEONG"::DOUBLE AS JEONSE_PRICE_PER_SUPPLY_PYEONG
FROM EXT_RDS_SNAPSHOT;



SELECT * FROM DAILY_REAL_ESTATE_TRADES;
