-- 01. FILE FORMAT 생성

CREATE OR REPLACE FILE FORMAT int_json_file_format
  TYPE = 'JSON'
  COMPRESSION = 'AUTO';


-- 02. INTERNAL STAGE 생성
CREATE OR REPLACE STAGE INT_JSON_FILE_STAGE 
  FILE_FORMAT = int_json_file_format;


-- > SNOWSQL로 LOCAL 파일을 STAGE로 업로드 후 아래 스크립트 실행

-- 03. STAGE에 업로드된 파일 목록 확인 
list @INT_JSON_FILE_STAGE;


-- 04. 임시로 확인할 테이블 생성
CREATE TABLE INT_TEMP_TEBLE (
  contents OBJECT
)

-- 04. 임시 테이블에 COPY INTO문을 이용하여 JSON 데이터를 TABLE로 변환
COPY INTO INT_TEMP_TEBLE
FROM @INT_JSON_FILE_STAGE
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'CONTINUE'

-- 05. 변환된 테이블 확인
SELECT * 
FROM INT_TEMP_TEBLE

-- 06. 각 ELEMENT를 컬럼으로 배치하여 테이블로 저장
CREATE TABLE DISTRICT_INCOME_CONSUMPTION AS
SELECT
  contents:"AE_132_SQMT_HSHLD_CO"::NUMBER      AS AE_132_SQMT_HSHLD_CO,
  contents:"AE_165_SQMT_HSHLD_CO"::NUMBER      AS AE_165_SQMT_HSHLD_CO,
  contents:"AE_66_SQMT_BELO_HSHLD_CO"::NUMBER  AS AE_66_SQMT_BELO_HSHLD_CO,
  contents:"AE_66_SQMT_HSHLD_CO"::NUMBER       AS AE_66_SQMT_HSHLD_CO,
  contents:"AE_99_SQMT_HSHLD_CO"::NUMBER       AS AE_99_SQMT_HSHLD_CO,
  contents:"APT_HSMP_CO"::NUMBER               AS APT_HSMP_CO,
  contents:"AVRG_AE"::NUMBER                   AS AVRG_AE,
  contents:"AVRG_MKTC"::NUMBER                 AS AVRG_MKTC,
  contents:"PC_1_HDMIL_BELO_HSHLD_CO"::NUMBER  AS PC_1_HDMIL_BELO_HSHLD_CO,
  contents:"PC_1_HDMIL_HSHLD_CO"::NUMBER       AS PC_1_HDMIL_HSHLD_CO,
  contents:"PC_2_HDMIL_HSHLD_CO"::NUMBER       AS PC_2_HDMIL_HSHLD_CO,
  contents:"PC_3_HDMIL_HSHLD_CO"::NUMBER       AS PC_3_HDMIL_HSHLD_CO,
  contents:"PC_4_HDMIL_HSHLD_CO"::NUMBER       AS PC_4_HDMIL_HSHLD_CO,
  contents:"PC_5_HDMIL_HSHLD_CO"::NUMBER       AS PC_5_HDMIL_HSHLD_CO,
  contents:"PC_6_HDMIL_ABOVE_HSHLD_CO"::NUMBER AS PC_6_HDMIL_ABOVE_HSHLD_CO,
  contents:"SIGNGU_CD"::STRING                 AS SIGNGU_CD,
  contents:"SIGNGU_CD_NM"::STRING              AS SIGNGU_CD_NM,
  contents:"STDR_YYQU_CD"::STRING              AS STDR_YYQU_CD
FROM INT_TEMP_TEBLE;


SELECT * FROM DISTRICT_INCOME_CONSUMPTION;
